# Generated by Django 5.1.4 on 2025-01-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='cc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
